name: Lambda-Bundler-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_python36:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Install Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install dev dependencies
        run: pip install -e ".[dev]"
      
      - name: Run Pytest
        run: pytest
