name: Lambda-Bundler-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Trigger on release, this will cause the upload to Pypi
  release:
    types:
      - created

jobs:

  build_python36:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      
      - name: Install Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install dev dependencies
        run: pip install -e ".[dev]"
      
      # - name: Run Pytest
      #   run: pytest --cov-report=xml

      - name: Upload coverage metrics
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_COVERAGE_REPORT}}
        with:
          coverageCommand: pytest --cov-report=xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py

      # - name: Upload coverage metrics
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
      
      - name: Run Pylint
        run: pylint lambda_bundler
      
      - name: Create distribution 📦
        run: python3 setup.py sdist bdist_wheel
      
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-packages
          path: dist/
    
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_LAMBDA_BUNDLER_TOKEN }}
